- kuksa-hawkbit/CheckNewSoftware.py
- kuksa-hawkbit/QueryPersonality.py
- kuksa-hawkbit/Readme.md
- kuksa-hawkbit/config.ini
Signed-off-by: Sebastian Schildt <sebastian.schildt@de.bosch.com>
> First version of Kuksa Hawkbit Downloader

- kuksa-hawkbit/QueryPersonality.py
Provide some functionality to communicate state back to Hawkbit.
Signed-off-by: Sebastian Schildt <sebastian.schildt@de.bosch.com>
> Providing feedback to Hawkbit

- w3c-visserver-api/README.md
Signed-off-by: Wagner Marco <Marco.Wagner3@de.bosch.com>
> Documentation for w3c API updated

- agl-kuksa/README.md
- agl-kuksa/tools/agl-configure.sh.configure
- agl-kuksa/tools/cmake/agl.cmake
* Modified Cmake scripts for Docker support.
Signed-off-by: Pratheek Rai <pratheek.rai@de.bosch.com>
> Modified cmake scripts for docker support

- direct-access-api/CMakeLists.txt
- direct-access-api/include/accesschecker.hpp
- direct-access-api/include/authenticator.hpp
- direct-access-api/include/common.hpp
- direct-access-api/include/dbmanager.hpp
- direct-access-api/include/directAccessProcessor.hpp
- direct-access-api/include/exception.hpp
- direct-access-api/include/obeclient.hpp
- direct-access-api/include/vcanhandler.hpp
- direct-access-api/include/wschannel.hpp
- direct-access-api/include/wsserver.hpp
- direct-access-api/src/authenticator.cpp
- direct-access-api/src/dbmanager.cpp
- direct-access-api/src/directAccessProcessor.cpp
- direct-access-api/src/obeclient.cpp
- direct-access-api/src/vcanhandler.cpp
- direct-access-api/src/wsserver.cpp
KoçSistem's first pull request for Direct Access API Kuksa In-vehicle platform.
> Added Direct Access API into Kuksa In-vehicle platform

- agl-kuksa/meta-kuksa/conf/layer.conf
- agl-kuksa/meta-kuksa/recipes-directacess-api/direct-access-api/direct-access-api_0.0.7.bb
- agl-kuksa/meta-kuksa/recipes-directacess-api/direct-access-api/files/LICENSE
- agl-kuksa/meta-kuksa/recipes-directacess-api/direct-access-api/files/dummy.txt
- direct-access-api/README.md
Updated README.md
Signed-off-by: Erdem Ergen <erdem.ergen@kocsistem.com.tr>
Using SQLite library and compatible with version 3.20.0
> Added Direct Access API recipe and layer.

- kuksa-appmanager/kuksa/appmanager/hawkbit.py
Signed-off-by: Markus Walther <Markus.Walther@de.bosch.com>
> Raise ConfigurationError when docker-container.json file does not exist

- w3c-visserver-api/.gitignore
- w3c-visserver-api/CMakeLists.txt
- w3c-visserver-api/include/exception.hpp
- w3c-visserver-api/include/vssdatabase.hpp
- w3c-visserver-api/include/wsserver.hpp
- w3c-visserver-api/src/main.cpp
- w3c-visserver-api/src/vsscommandprocessor.cpp
- w3c-visserver-api/src/vssdatabase.cpp
- w3c-visserver-api/src/wsserver.cpp
- w3c-visserver-api/unit-test/CMakeLists.txt
- w3c-visserver-api/unit-test/readme.md
- w3c-visserver-api/unit-test/w3cunittest.cpp
- w3c-visserver-api/unit-test/w3cunittest.hpp
Signed-off-by: Pratheek Rai <pratheek.rai@de.bosch.com>
* Added BOOST based unit tests for W3C-VIS Server. This depends on version >= 1.59.
> Unit test cases for w3c-visserver

- kuksa-appmanager/kuksa/appmanager/hawkbit.py
- kuksa-appmanager/kuksa/appmanager/services.py
Signed-off-by: Markus Walther <Markus.Walther@de.bosch.com>
> Add function to stop and remove all kuksa tagged docker container

- w3c-visserver-api/README.md
- w3c-visserver-api/include/signing.hpp
- w3c-visserver-api/include/visconf.hpp
- w3c-visserver-api/include/vsscommandprocessor.hpp
- w3c-visserver-api/src/signing.cpp
- w3c-visserver-api/src/vsscommandprocessor.cpp
- w3c-visserver-api/unit-test/CMakeLists.txt
- w3c-visserver-api/unit-test/w3cunittest.cpp
* Added JSON Signing capability for data integrity. 
* This feature needs to be manually enabled and by default it is disabled.
* This is a work in progress and will also be integrated with Authentication/Authorization process, which is also coming soon.
> Json signing for VSS data unit test and POC

- agl-kuksa/README.md
Signed-off-by: Kevin Goez <kevin.goez@de.bosch.com>
> add build information for the cm3

- elm327-visdatafeeder/src/main.cpp
- elm327-visdatafeeder/src/obd.cpp
- elm327-visdatafeeder/src/vssMapper.cpp
* Updated elm327-visdatafeeder to make it work optimally with the kuksa-dongle.
> Updated elm327-visdatafeeder to work with max baud rate on kuksa dongle

- elm327-visdatafeeder/src/vssMapper.cpp
Signed-off-by: Pratheek Rai <pratheek.rai@de.bosch.com>
> Fixed the bug with fuel data translation

- agl-kuksa/README.md
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/conf/layer.conf
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/meta-raspberrypi/recipes-kuksa-fota/kuksa-fota/files/LICENSE
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/meta-raspberrypi/recipes-kuksa-fota/kuksa-fota/files/kuksa-firmware-flash
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/meta-raspberrypi/recipes-kuksa-fota/kuksa-fota/files/kuksa-firmware-get-version
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/meta-raspberrypi/recipes-kuksa-fota/kuksa-fota/kuksa-fota_0.1.0.bb
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/recipes-kuksa-fota/kuksa-fota/files/LICENSE
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/recipes-kuksa-fota/kuksa-fota/files/kuksa-firmware-dummy
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/recipes-kuksa-fota/kuksa-fota/kuksa-fota_0.0.0.bb
- agl-kuksa/meta-kuksa/meta-kuksa-bsp/wic/sdimage-raspberrypi.wks
- agl-kuksa/tools/cmake/agl.cmake
- fota-raspberrypi/README.md
Signed-off-by: Sven Schoenberg <sven.schoenberg@c-lab.de>
> AGL recipes for Raspberry Pi FOTA scripts in new meta-kuksa-bsp layer

- agl-kuksa/meta-kuksa/recipes-devtools/python/python3-docker_3.4.0.bb
- agl-kuksa/meta-kuksa/recipes-devtools/python/python3-docker_3.6.0.bb
Signed-off-by: Sven Schoenberg <sven.schoenberg@c-lab.de>
> Bump python3-docker to 3.6.0 - fixes #73

- w3c-visserver-api/CMakeLists.txt
- w3c-visserver-api/include/authenticator.hpp
- w3c-visserver-api/src/authenticator.cpp
- w3c-visserver-api/src/subscriptionhandler.cpp
- w3c-visserver-api/src/vsscommandprocessor.cpp
- w3c-visserver-api/src/wsserver.cpp
- w3c-visserver-api/unit-test/CMakeLists.txt
- Fix non-void functions not returning anything
- Initialize uninitialized memory before use
- Enable all warnings
Signed-off-by: John Argérus <john.argerus@se.bosch.com>
> Fix undefined behaviour bugs (and some compiler warnings)

- agl-kuksa/meta-kuksa/recipes-gps-visfeeder/gps-visfeeder/gps-visfeeder.bb
- kuksa-dongle/internet-status.py
Removed wiringpi dependancy.
Updated the LICENSE checksum in the recipe.
**Please merge this to the kuksa-obd-dongle-components branch**
Signed-off-by: Pratheek Rai <pratheek.rai@de.bosch.com>
> Some quick fix for kuksa dongle

- w3c-visserver-api/src/vssdatabase.cpp
Signed-off-by: John Argérus <john.argerus@se.bosch.com>
> Accept all valid float and double values

- elm327-visdatafeeder/src/main.cpp
- elm327-visdatafeeder/src/vssMapper.cpp
- w3c-visserver-api/include/subscriptionhandler.hpp
- w3c-visserver-api/src/subscriptionhandler.cpp
- w3c-visserver-api/src/vssdatabase.cpp
- w3c-visserver-api/unit-test/vss_rel_2.0.json
- w3c-visserver-api/unit-test/w3cunittest.cpp
- Update data model in accordance with new W3C standard (vss2.0).
- Update unit tests.
Signed-off-by: John Argérus <john.argerus@se.bosch.com>
> Update visserver & visfeeder for new W3C standard

- agl-kuksa/meta-kuksa/recipes-kuksa-appmanager/kuksa-appmanager/files/kuksa-appmanager.service
Signed-off-by: Sven Schoenberg <sven.schoenberg@c-lab.de>
> AppManager restarts on failure - fixes #83

- TEST_RESULTS.md
- w3c-visserver-api/unit-test/w3cunittest.cpp
- Added test results file
- Added subscription unit tests
- Added expected failure test annotations
> Test results release

- w3c-visserver-api/CMakeLists.txt
Signed-off-by: Miladinovic Bojan (RBSN/ESW22) <fixed-term.bojan.miladinovic@se.bosch.com>
> Add VSS json file to build and install directory

- w3c-visserver-api/src/vsscommandprocessor.cpp
- w3c-visserver-api/src/vssdatabase.cpp
- w3c-visserver-api/unit-test/w3cunittest.cpp
Signed-off-by: John Argérus <john.argerus@se.bosch.com>
> Handle malformed requests

- kuksa-appmanager/kuksa/appmanager/hawkbit.py
- kuksa-appmanager/kuksa/appmanager/services.py
Cleans up after redeploying up, otherwise disk will fill up with old containers.
Note: On API 1.25 of docker (or the used python docker API, tested until 4.01) the return value for the used REST call is wrong, so it will always print 0 reclaimed bytes in debug logging. However, stales containers are in fact deleted. I kept the logging, so it will work once the APIs are repaired.
The code only touches containers managed by Appmanager, it will not touch unused containers which have been installed by other means than Appmamanager
@rai20 @daschubert 
fixes #102
> Clean up unused managed containers after deployment

- kuksa-appmanager/kuksa/appmanager/__main__.py
Quick fix for #107 
Check @rai20  or @m-lenz
Merge @daschubert 
:cake:
> Remove trailing slashes in hawkbit server config

- README.md
- kuksa-appmanager/README.md
- kuksa-appmanager/kuksa/appmanager/appregistry.py
- kuksa-appmanager/kuksa/appmanager/hawkbit.py
- kuksa-appmanager/kuksa/appmanager/widgets.py
- kuksa-appmanager/wiki/widgets.md
Signed-off-by: Sven Schoenberg <sven.schoenberg@c-lab.de>
> AppManager AGL widget support

- kuksa-dongle/README.md
- kuksa-dongle/docs/README.md
This PR contains information about setting up the Kuksa Dongle and respecitve OS and configurations of the OBD-II connector.
> Doc/kuksa dongle/setup guide

- kuksa-dongle/docs/README.md
Minor changes in the documentation and fixing some typos in OBD configuration commands
> fix minor documentation issues in the OBD configuration instructions
